apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: l9if64pt2-nodejs 
  janus-idp.io/tekton: l9if64pt2-nodejs
  backstage.io/kubernetes-id: l9if64pt2-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: l9if64pt2-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml